//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourism3D.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ModelSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ModelSettings defaultInstance = ((ModelSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ModelSettings())));
        
        public static ModelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string CasteloAdjustment {
            get {
                return ((string)(this["CasteloAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,0")]
        public string CasteloDimensions {
            get {
                return ((string)(this["CasteloDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string CasteloSoundName {
            get {
                return ((string)(this["CasteloSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-2,0")]
        public string WaygateAdjustment {
            get {
                return ((string)(this["WaygateAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,3")]
        public string WaygateDimensions {
            get {
                return ((string)(this["WaygateDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GryphonAviaryWhat1.wav")]
        public string WaygateSoundName {
            get {
                return ((string)(this["WaygateSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-3,0")]
        public string CityBuildingSmall0_0Adjustment {
            get {
                return ((string)(this["CityBuildingSmall0_0Adjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|5,0")]
        public string CityBuildingSmall0_0Dimensions {
            get {
                return ((string)(this["CityBuildingSmall0_0Dimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GryphonAviaryWhat1.wav")]
        public string CityBuildingSmall0_0SoundName {
            get {
                return ((string)(this["CityBuildingSmall0_0SoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,0")]
        public string WorkshopAdjustment {
            get {
                return ((string)(this["WorkshopAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|3,0")]
        public string WorkshopDimensions {
            get {
                return ((string)(this["WorkshopDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GryphonAviaryWhat1.wav")]
        public string WorkshopSoundName {
            get {
                return ((string)(this["WorkshopSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|0,0")]
        public string GryphonAviaryAdjustment {
            get {
                return ((string)(this["GryphonAviaryAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,0")]
        public string GryphonAviaryDimensions {
            get {
                return ((string)(this["GryphonAviaryDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GryphonAviaryWhat1.wav")]
        public string GryphonAviarySoundName {
            get {
                return ((string)(this["GryphonAviarySoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string AltarOfKingsAdjustment {
            get {
                return ((string)(this["AltarOfKingsAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,0")]
        public string AltarOfKingsDimensions {
            get {
                return ((string)(this["AltarOfKingsDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string AltarOfKingsSoundName {
            get {
                return ((string)(this["AltarOfKingsSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,0|0,0|0,0")]
        public string HumanBarracksAdjustment {
            get {
                return ((string)(this["HumanBarracksAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|3,0")]
        public string HumanBarracksDimensions {
            get {
                return ((string)(this["HumanBarracksDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkshopWhat1.wav")]
        public string HumanBarracksSoundName {
            get {
                return ((string)(this["HumanBarracksSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,5|0,0|-2,0")]
        public string BridgeObeliskAdjustment {
            get {
                return ((string)(this["BridgeObeliskAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,0|1,0|1,0")]
        public string BridgeObeliskDimensions {
            get {
                return ((string)(this["BridgeObeliskDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string BridgeObeliskSoundName {
            get {
                return ((string)(this["BridgeObeliskSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string DragonRoostBlackAdjustment {
            get {
                return ((string)(this["DragonRoostBlackAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|3,5")]
        public string DragonRoostBlackDimensions {
            get {
                return ((string)(this["DragonRoostBlackDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkshopWhat1.wav")]
        public string DragonRoostBlackSoundName {
            get {
                return ((string)(this["DragonRoostBlackSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string FrostmourneAdjustment {
            get {
                return ((string)(this["FrostmourneAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,0|1,0|1,0")]
        public string FrostmourneDimensions {
            get {
                return ((string)(this["FrostmourneDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string FrostmourneSoundName {
            get {
                return ((string)(this["FrostmourneSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|0,0")]
        public string AltarOfEldersAdjustment {
            get {
                return ((string)(this["AltarOfEldersAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|3,5")]
        public string AltarOfEldersDimensions {
            get {
                return ((string)(this["AltarOfEldersDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string AltarOfEldersSoundName {
            get {
                return ((string)(this["AltarOfEldersSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string GraveyardAdjustment {
            get {
                return ((string)(this["GraveyardAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,0")]
        public string GraveyardDimensions {
            get {
                return ((string)(this["GraveyardDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string GraveyardSoundName {
            get {
                return ((string)(this["GraveyardSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string BearDenAdjustment {
            get {
                return ((string)(this["BearDenAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,0")]
        public string BearDenDimensions {
            get {
                return ((string)(this["BearDenDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string BearDenSoundName {
            get {
                return ((string)(this["BearDenSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-2,5")]
        public string TreeofLifeAdjustment {
            get {
                return ((string)(this["TreeofLifeAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,0|1,0|2,5")]
        public string TreeofLifeDimensions {
            get {
                return ((string)(this["TreeofLifeDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltarOfKingsWhat1")]
        public string TreeofLifeSoundName {
            get {
                return ((string)(this["TreeofLifeSoundName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0|0,0|-1,5")]
        public string TownHallAdjustment {
            get {
                return ((string)(this["TownHallAdjustment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4,0|1,0|3,0")]
        public string TownHallDimensions {
            get {
                return ((string)(this["TownHallDimensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkshopWhat1.wav")]
        public string TownHallSoundName {
            get {
                return ((string)(this["TownHallSoundName"]));
            }
        }
    }
}
