//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourism3D.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyTourism3D.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características da Atracção.
        /// </summary>
        internal static string AttractionFeatures {
            get {
                return ResourceManager.GetString("AttractionFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Autenticaçao falhou. Verifique os seu Nome de Utilizador e Password e tente de novo..
        /// </summary>
        internal static string AuthenticationFailedException {
            get {
                return ResourceManager.GetString("AuthenticationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carregar Modelos 3DS....
        /// </summary>
        internal static string Loading3DS {
            get {
                return ResourceManager.GetString("Loading3DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carregar Sons....
        /// </summary>
        internal static string LoadingSounds {
            get {
                return ResourceManager.GetString("LoadingSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carregar Texturas....
        /// </summary>
        internal static string LoadingTextures {
            get {
                return ResourceManager.GetString("LoadingTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar Música Ambiente.
        /// </summary>
        internal static string MenuSwitchAmbientMusic {
            get {
                return ResourceManager.GetString("MenuSwitchAmbientMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Música 1.
        /// </summary>
        internal static string Music1 {
            get {
                return ResourceManager.GetString("Music1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Música 2.
        /// </summary>
        internal static string Music2 {
            get {
                return ResourceManager.GetString("Music2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há Pontos de Interesse para visitar.
        /// </summary>
        internal static string NoPOIsToVisit {
            get {
                return ResourceManager.GetString("NoPOIsToVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Velocidade da Simulação mudou para.
        /// </summary>
        internal static string SimulationSpeedChanged {
            get {
                return ResourceManager.GetString("SimulationSpeedChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapidinho.
        /// </summary>
        internal static string SimulationSpeedFast {
            get {
                return ResourceManager.GetString("SimulationSpeedFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rápido.
        /// </summary>
        internal static string SimulationSpeedFaster {
            get {
                return ResourceManager.GetString("SimulationSpeedFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string SimulationSpeedNormal {
            get {
                return ResourceManager.GetString("SimulationSpeedNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito Rápido!.
        /// </summary>
        internal static string SimulationSpeedSuperFast {
            get {
                return ResourceManager.GetString("SimulationSpeedSuperFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua rota não foi gravada provavelmente devido a problemas de Base de Dados ou de Autenticação..
        /// </summary>
        internal static string TourNotSavedException {
            get {
                return ResourceManager.GetString("TourNotSavedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminou a Visita!.
        /// </summary>
        internal static string TourOver {
            get {
                return ResourceManager.GetString("TourOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Visita terminou. Prima ESC para sair..
        /// </summary>
        internal static string TourOverPressESC {
            get {
                return ResourceManager.GetString("TourOverPressESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atracções a Visitar.
        /// </summary>
        internal static string ToVisitLabel {
            get {
                return ResourceManager.GetString("ToVisitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitado.
        /// </summary>
        internal static string VisitedLabel {
            get {
                return ResourceManager.GetString("VisitedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpo.
        /// </summary>
        internal static string WeatherStateClear {
            get {
                return ResourceManager.GetString("WeatherStateClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevoeiro.
        /// </summary>
        internal static string WeatherStateFoggy {
            get {
                return ResourceManager.GetString("WeatherStateFoggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo:.
        /// </summary>
        internal static string WeatherStateLabel {
            get {
                return ResourceManager.GetString("WeatherStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuvoso.
        /// </summary>
        internal static string WeatherStateRainy {
            get {
                return ResourceManager.GetString("WeatherStateRainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neve.
        /// </summary>
        internal static string WeatherStateSnowy {
            get {
                return ResourceManager.GetString("WeatherStateSnowy", resourceCulture);
            }
        }
    }
}
