//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace EasyTourism3D.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EasyTourismServicesSoap", Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class EasyTourismServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveTourOperationCompleted;
        
        private System.Threading.SendOrPostCallback SVGMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback CSVMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback CityCartographyMinifiedOperationCompleted;
        
        private System.Threading.SendOrPostCallback CityCartographyFullOperationCompleted;
        
        private System.Threading.SendOrPostCallback TourListForTouristOperationCompleted;
        
        private System.Threading.SendOrPostCallback TourForTouristOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EasyTourismServices() {
            this.Url = global::EasyTourism3D.Properties.Settings.Default.EasyTourism3D_WebService_EasyTourismServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveTourCompletedEventHandler SaveTourCompleted;
        
        /// <remarks/>
        public event SVGMapCompletedEventHandler SVGMapCompleted;
        
        /// <remarks/>
        public event CSVMapCompletedEventHandler CSVMapCompleted;
        
        /// <remarks/>
        public event CityCartographyMinifiedCompletedEventHandler CityCartographyMinifiedCompleted;
        
        /// <remarks/>
        public event CityCartographyFullCompletedEventHandler CityCartographyFullCompleted;
        
        /// <remarks/>
        public event TourListForTouristCompletedEventHandler TourListForTouristCompleted;
        
        /// <remarks/>
        public event TourForTouristCompletedEventHandler TourForTouristCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/SaveTour", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveTour(string username, string password, int tourID, ToVisit[] list) {
            object[] results = this.Invoke("SaveTour", new object[] {
                        username,
                        password,
                        tourID,
                        list});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveTourAsync(string username, string password, int tourID, ToVisit[] list) {
            this.SaveTourAsync(username, password, tourID, list, null);
        }
        
        /// <remarks/>
        public void SaveTourAsync(string username, string password, int tourID, ToVisit[] list, object userState) {
            if ((this.SaveTourOperationCompleted == null)) {
                this.SaveTourOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveTourOperationCompleted);
            }
            this.InvokeAsync("SaveTour", new object[] {
                        username,
                        password,
                        tourID,
                        list}, this.SaveTourOperationCompleted, userState);
        }
        
        private void OnSaveTourOperationCompleted(object arg) {
            if ((this.SaveTourCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveTourCompleted(this, new SaveTourCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/SVGMap", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SVGMap(int cityID) {
            object[] results = this.Invoke("SVGMap", new object[] {
                        cityID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SVGMapAsync(int cityID) {
            this.SVGMapAsync(cityID, null);
        }
        
        /// <remarks/>
        public void SVGMapAsync(int cityID, object userState) {
            if ((this.SVGMapOperationCompleted == null)) {
                this.SVGMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSVGMapOperationCompleted);
            }
            this.InvokeAsync("SVGMap", new object[] {
                        cityID}, this.SVGMapOperationCompleted, userState);
        }
        
        private void OnSVGMapOperationCompleted(object arg) {
            if ((this.SVGMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SVGMapCompleted(this, new SVGMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/CSVMap", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CSVMap(int cityID) {
            this.Invoke("CSVMap", new object[] {
                        cityID});
        }
        
        /// <remarks/>
        public void CSVMapAsync(int cityID) {
            this.CSVMapAsync(cityID, null);
        }
        
        /// <remarks/>
        public void CSVMapAsync(int cityID, object userState) {
            if ((this.CSVMapOperationCompleted == null)) {
                this.CSVMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCSVMapOperationCompleted);
            }
            this.InvokeAsync("CSVMap", new object[] {
                        cityID}, this.CSVMapOperationCompleted, userState);
        }
        
        private void OnCSVMapOperationCompleted(object arg) {
            if ((this.CSVMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CSVMapCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/CityCartographyMinified", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cartography CityCartographyMinified(int cityID) {
            object[] results = this.Invoke("CityCartographyMinified", new object[] {
                        cityID});
            return ((Cartography)(results[0]));
        }
        
        /// <remarks/>
        public void CityCartographyMinifiedAsync(int cityID) {
            this.CityCartographyMinifiedAsync(cityID, null);
        }
        
        /// <remarks/>
        public void CityCartographyMinifiedAsync(int cityID, object userState) {
            if ((this.CityCartographyMinifiedOperationCompleted == null)) {
                this.CityCartographyMinifiedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCityCartographyMinifiedOperationCompleted);
            }
            this.InvokeAsync("CityCartographyMinified", new object[] {
                        cityID}, this.CityCartographyMinifiedOperationCompleted, userState);
        }
        
        private void OnCityCartographyMinifiedOperationCompleted(object arg) {
            if ((this.CityCartographyMinifiedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CityCartographyMinifiedCompleted(this, new CityCartographyMinifiedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/CityCartographyFull", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cartography CityCartographyFull(int cityID) {
            object[] results = this.Invoke("CityCartographyFull", new object[] {
                        cityID});
            return ((Cartography)(results[0]));
        }
        
        /// <remarks/>
        public void CityCartographyFullAsync(int cityID) {
            this.CityCartographyFullAsync(cityID, null);
        }
        
        /// <remarks/>
        public void CityCartographyFullAsync(int cityID, object userState) {
            if ((this.CityCartographyFullOperationCompleted == null)) {
                this.CityCartographyFullOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCityCartographyFullOperationCompleted);
            }
            this.InvokeAsync("CityCartographyFull", new object[] {
                        cityID}, this.CityCartographyFullOperationCompleted, userState);
        }
        
        private void OnCityCartographyFullOperationCompleted(object arg) {
            if ((this.CityCartographyFullCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CityCartographyFullCompleted(this, new CityCartographyFullCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/TourListForTourist", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TourList TourListForTourist(string username, string password) {
            object[] results = this.Invoke("TourListForTourist", new object[] {
                        username,
                        password});
            return ((TourList)(results[0]));
        }
        
        /// <remarks/>
        public void TourListForTouristAsync(string username, string password) {
            this.TourListForTouristAsync(username, password, null);
        }
        
        /// <remarks/>
        public void TourListForTouristAsync(string username, string password, object userState) {
            if ((this.TourListForTouristOperationCompleted == null)) {
                this.TourListForTouristOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTourListForTouristOperationCompleted);
            }
            this.InvokeAsync("TourListForTourist", new object[] {
                        username,
                        password}, this.TourListForTouristOperationCompleted, userState);
        }
        
        private void OnTourListForTouristOperationCompleted(object arg) {
            if ((this.TourListForTouristCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TourListForTouristCompleted(this, new TourListForTouristCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dot.dei.isep.ipp.pt/jarasoft/Dir2/TourForTourist", RequestNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", ResponseNamespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour TourForTourist(string username, string password, int tourID) {
            object[] results = this.Invoke("TourForTourist", new object[] {
                        username,
                        password,
                        tourID});
            return ((Tour)(results[0]));
        }
        
        /// <remarks/>
        public void TourForTouristAsync(string username, string password, int tourID) {
            this.TourForTouristAsync(username, password, tourID, null);
        }
        
        /// <remarks/>
        public void TourForTouristAsync(string username, string password, int tourID, object userState) {
            if ((this.TourForTouristOperationCompleted == null)) {
                this.TourForTouristOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTourForTouristOperationCompleted);
            }
            this.InvokeAsync("TourForTourist", new object[] {
                        username,
                        password,
                        tourID}, this.TourForTouristOperationCompleted, userState);
        }
        
        private void OnTourForTouristOperationCompleted(object arg) {
            if ((this.TourForTouristCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TourForTouristCompleted(this, new TourForTouristCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class ToVisit : PointOfInterest {
        
        private bool visitedField;
        
        private int orderingField;
        
        private System.DateTime beginVisitField;
        
        private System.DateTime endVisitField;
        
        /// <remarks/>
        public bool visited {
            get {
                return this.visitedField;
            }
            set {
                this.visitedField = value;
            }
        }
        
        /// <remarks/>
        public int ordering {
            get {
                return this.orderingField;
            }
            set {
                this.orderingField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime beginVisit {
            get {
                return this.beginVisitField;
            }
            set {
                this.beginVisitField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime endVisit {
            get {
                return this.endVisitField;
            }
            set {
                this.endVisitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ToVisit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class PointOfInterest {
        
        private int idField;
        
        private int segmentIDField;
        
        private string nameField;
        
        private string modelField;
        
        private Vector3D positionField;
        
        private string descriptionField;
        
        private string[] featuresField;
        
        private string[] restrictionsField;
        
        private string typeField;
        
        private string classificationField;
        
        private string facingField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int segmentID {
            get {
                return this.segmentIDField;
            }
            set {
                this.segmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string[] features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
            }
        }
        
        /// <remarks/>
        public string[] restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        public string facing {
            get {
                return this.facingField;
            }
            set {
                this.facingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class Vector3D {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class Tour {
        
        private bool authenticatedField;
        
        private int tourIDField;
        
        private int cityIDField;
        
        private string cityNameField;
        
        private System.DateTime beginField;
        
        private ToVisit[] toVisitField;
        
        /// <remarks/>
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        public int tourID {
            get {
                return this.tourIDField;
            }
            set {
                this.tourIDField = value;
            }
        }
        
        /// <remarks/>
        public int cityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
            }
        }
        
        /// <remarks/>
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        public ToVisit[] toVisit {
            get {
                return this.toVisitField;
            }
            set {
                this.toVisitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class TourList {
        
        private bool authenticatedField;
        
        private int touristIDField;
        
        private Tour[] toursField;
        
        /// <remarks/>
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        public int touristID {
            get {
                return this.touristIDField;
            }
            set {
                this.touristIDField = value;
            }
        }
        
        /// <remarks/>
        public Tour[] tours {
            get {
                return this.toursField;
            }
            set {
                this.toursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class GenericObject {
        
        private int idField;
        
        private Vector3D positionField;
        
        private string typeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class RoadSegment {
        
        private int idField;
        
        private string nameField;
        
        private int idIntersectionBeginField;
        
        private int idIntersectionEndField;
        
        private double avgByCarField;
        
        private double avgByFootField;
        
        private int wayField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int idIntersectionBegin {
            get {
                return this.idIntersectionBeginField;
            }
            set {
                this.idIntersectionBeginField = value;
            }
        }
        
        /// <remarks/>
        public int idIntersectionEnd {
            get {
                return this.idIntersectionEndField;
            }
            set {
                this.idIntersectionEndField = value;
            }
        }
        
        /// <remarks/>
        public double avgByCar {
            get {
                return this.avgByCarField;
            }
            set {
                this.avgByCarField = value;
            }
        }
        
        /// <remarks/>
        public double avgByFoot {
            get {
                return this.avgByFootField;
            }
            set {
                this.avgByFootField = value;
            }
        }
        
        /// <remarks/>
        public int way {
            get {
                return this.wayField;
            }
            set {
                this.wayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class Intersection {
        
        private int idField;
        
        private Vector3D positionField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dot.dei.isep.ipp.pt/jarasoft/Dir2/")]
    public partial class Cartography {
        
        private PointOfInterest[] pointsOfInterestField;
        
        private Intersection[] intersectionsField;
        
        private RoadSegment[] roadSegmentsField;
        
        private GenericObject[] genericObjectsField;
        
        /// <remarks/>
        public PointOfInterest[] pointsOfInterest {
            get {
                return this.pointsOfInterestField;
            }
            set {
                this.pointsOfInterestField = value;
            }
        }
        
        /// <remarks/>
        public Intersection[] intersections {
            get {
                return this.intersectionsField;
            }
            set {
                this.intersectionsField = value;
            }
        }
        
        /// <remarks/>
        public RoadSegment[] roadSegments {
            get {
                return this.roadSegmentsField;
            }
            set {
                this.roadSegmentsField = value;
            }
        }
        
        /// <remarks/>
        public GenericObject[] genericObjects {
            get {
                return this.genericObjectsField;
            }
            set {
                this.genericObjectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SaveTourCompletedEventHandler(object sender, SaveTourCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveTourCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveTourCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SVGMapCompletedEventHandler(object sender, SVGMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SVGMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SVGMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CSVMapCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CityCartographyMinifiedCompletedEventHandler(object sender, CityCartographyMinifiedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CityCartographyMinifiedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CityCartographyMinifiedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cartography Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cartography)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CityCartographyFullCompletedEventHandler(object sender, CityCartographyFullCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CityCartographyFullCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CityCartographyFullCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cartography Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cartography)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TourListForTouristCompletedEventHandler(object sender, TourListForTouristCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TourListForTouristCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TourListForTouristCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TourList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TourList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TourForTouristCompletedEventHandler(object sender, TourForTouristCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TourForTouristCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TourForTouristCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591